### ISSUE TITLE
Example on http://outsidemybox.github.io/testUtils/ is just wrong

### ISSUE THREAD

**Issue by db-dpp** [outsideMyBox/testUtils#2]
On http://outsidemybox.github.io/testUtils/ there is an example with a class MyBean, it has 3 properties, of those 2 are used in the equals method, and all three are used in the hashcode method.
This should be the other way around, see javadoc : http://docs.oracle.com/javase/7/docs/api/java/lang/Object.html#hashCode()
"If two objects are equal according to the equals(Object) method, then calling the hashCode method on each of the two objects must produce the same integer result."
Writing such examples can prove a bad influence on inexperienced programmers.

**Comment by outsideMyBox** [comment]
Thanks for your comment. Actually property3 is superfluous in both equals() and hashCode() (it's a readonly property), I've removed it from the example.
